// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice =
  | CardsSlice
  | FeatureSlice
  | ContentListSlice
  | LargeMediaSlice
  | ImageGridSlice
  | SimpleHeroSlice
  | AccordionSectionSlice
  | HeroSlice
  | TextSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Layout → Links*
 */
export interface LayoutDocumentDataLinksItem {
  /**
   * Link field in *Layout → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add a single link or a list of links (for dropdown menu)
   * - **API ID Path**: layout.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Layout → Links 1*
 */
export interface LayoutDocumentDataLinks1Item {
  /**
   * Link field in *Layout → Links 1*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links_1[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Layout → Social Links*
 */
export interface LayoutDocumentDataSocialLinksItem {
  /**
   * Link field in *Layout → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon field in *Layout → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_links[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * Links field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<LayoutDocumentDataLinksItem>>;

  /**
   * CTA field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.cta
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >; /**
   * Text field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Descriptive text to accompany logo
   * - **API ID Path**: layout.text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Links Title 1 field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links_title_1
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  links_title_1: prismic.KeyTextField;

  /**
   * Links 1 field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.links_1[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links_1: prismic.GroupField<Simplify<LayoutDocumentDataLinks1Item>>;

  /**
   * Social Links field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.social_links[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<Simplify<LayoutDocumentDataSocialLinksItem>>;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | CardsSlice
  | FeatureSlice
  | ContentListSlice
  | AccordionSectionSlice
  | LargeMediaSlice
  | ImageGridSlice
  | SimpleHeroSlice
  | HeroSlice
  | TextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField; /**
   * Preview image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.preview_image
   * - **Tab**: Preview Card Content
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  preview_image: prismic.ImageField<never>;

  /**
   * Excerpt field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.excerpt
   * - **Tab**: Preview Card Content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Preview Vimeo field in *Page*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: page.preview_vimeo
   * - **Tab**: Preview Card Content
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  preview_vimeo: prismic.EmbedField;

  /**
   * Preview Video field in *Page*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: page.preview_video
   * - **Tab**: Preview Card Content
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  preview_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * video poster image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.video_poster_image
   * - **Tab**: Preview Card Content
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  video_poster_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Room → Features*
 */
export interface RoomDocumentDataFeaturesItem {
  /**
   * Feature field in *Room → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room.features[].feature
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  feature: prismic.KeyTextField;
}

type RoomDocumentDataSlicesSlice = ImageGridSlice;

/**
 * Content for Room documents
 */
interface RoomDocumentData {
  /**
   * Title field in *Room*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Beds field in *Room*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room.beds
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  beds: prismic.KeyTextField;

  /**
   * Guests field in *Room*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room.guests
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  guests: prismic.KeyTextField;

  /**
   * Bath field in *Room*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room.bath
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bath: prismic.KeyTextField;

  /**
   * Description field in *Room*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Features field in *Room*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: room.features[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<Simplify<RoomDocumentDataFeaturesItem>>;

  /**
   * Book now link field in *Room*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: room.book_now_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  book_now_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Room*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: room.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<RoomDocumentDataSlicesSlice>; /**
   * Meta Title field in *Room*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: room.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Room*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: room.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Room*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: room.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>; /**
   * Preview image field in *Room*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: room.preview_image
   * - **Tab**: Preview Card Content
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  preview_image: prismic.ImageField<never>;

  /**
   * Excerpt field in *Room*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: room.excerpt
   * - **Tab**: Preview Card Content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Preview Vimeo field in *Room*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: room.preview_vimeo
   * - **Tab**: Preview Card Content
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  preview_vimeo: prismic.EmbedField;

  /**
   * Preview Video field in *Room*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: room.preview_video
   * - **Tab**: Preview Card Content
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  preview_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Video poster image field in *Room*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: room.video_poster_image
   * - **Tab**: Preview Card Content
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  video_poster_image: prismic.ImageField<never>;
}

/**
 * Room document from Prismic
 *
 * - **API ID**: `room`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RoomDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<RoomDocumentData>, "room", Lang>;

export type AllDocumentTypes =
  | HomeDocument
  | LayoutDocument
  | PageDocument
  | RoomDocument;

/**
 * Item in *AccordionSection → Default → Primary → Items*
 */
export interface AccordionSectionSliceDefaultPrimaryItemsItem {
  /**
   * Title field in *AccordionSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *AccordionSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Accordion content
   * - **API ID Path**: accordion_section.default.primary.items[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *AccordionSection → Default → Primary*
 */
export interface AccordionSectionSliceDefaultPrimary {
  /**
   * H2 field in *AccordionSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: If not filled then title will be h2
   * - **API ID Path**: accordion_section.default.primary.heading_2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading_2: prismic.RichTextField;

  /**
   * Title field in *AccordionSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Items field in *AccordionSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: accordion_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<AccordionSectionSliceDefaultPrimaryItemsItem>
  >;

  /**
   * Background Colour field in *AccordionSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: accordion_section.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_colour: prismic.SelectField<
    "Default" | "Variation 1" | "Variation 2",
    "filled"
  >;
}

/**
 * Default variation for AccordionSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccordionSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AccordionSection*
 */
type AccordionSectionSliceVariation = AccordionSectionSliceDefault;

/**
 * AccordionSection Shared Slice
 *
 * - **API ID**: `accordion_section`
 * - **Description**: AccordionSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AccordionSectionSlice = prismic.SharedSlice<
  "accordion_section",
  AccordionSectionSliceVariation
>;

/**
 * Item in *Cards → Default → Primary → Cards*
 */
export interface CardsSliceDefaultPrimaryCardsItem {
  /**
   * Title field in *Cards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Cards → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cards[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * CTA field in *Cards → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cards[].cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon (from fonts.google.com/icons) field in *Cards → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
  /**
   * Heading 2 field in *Cards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.heading_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading_2: prismic.KeyTextField;

  /**
   * Title field in *Cards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Cards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background Colour field in *Cards → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: cards.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_colour: prismic.SelectField<
    "Default" | "Variation 1" | "Variation 2",
    "filled"
  >;

  /**
   * Cards Colour field in *Cards → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: cards.default.primary.cards_colour
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  cards_colour: prismic.SelectField<
    "Default" | "Variation 1" | "Variation 2",
    "filled"
  >;

  /**
   * Columns field in *Cards → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Three
   * - **API ID Path**: cards.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  columns: prismic.SelectField<"Three" | "Four", "filled">;

  /**
   * Cards field in *Cards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<CardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardsSlice = prismic.SharedSlice<"cards", CardsSliceVariation>;

/**
 * Item in *ContentList → Default → Primary → Content*
 */
export interface ContentListSliceDefaultPrimaryContentItem {
  /**
   * Room field in *ContentList → Default → Primary → Content*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: content_list.default.primary.content[].room
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  room: ContentRelationshipFieldWithData<
    [
      {
        id: "room";
        fields: [
          "title",
          "beds",
          "guests",
          "bath",
          "description",
          "preview_image",
          "preview_vimeo",
          "preview_video",
          "video_poster_image",
        ];
      },
    ]
  >;
}

/**
 * Primary content in *ContentList → Default → Primary*
 */
export interface ContentListSliceDefaultPrimary {
  /**
   * H2 field in *ContentList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: If not filled then title will be h2
   * - **API ID Path**: content_list.default.primary.heading_2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading_2: prismic.RichTextField;

  /**
   * Title field in *ContentList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *ContentList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content_list.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  content: prismic.GroupField<
    Simplify<ContentListSliceDefaultPrimaryContentItem>
  >;

  /**
   * CTA field in *ContentList → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: content_list.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Background Colour field in *ContentList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: content_list.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_colour: prismic.SelectField<
    "Default" | "Variation 1" | "Variation 2",
    "filled"
  >;
}

/**
 * Default variation for ContentList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentList*
 */
type ContentListSliceVariation = ContentListSliceDefault;

/**
 * ContentList Shared Slice
 *
 * - **API ID**: `content_list`
 * - **Description**: ContentList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentListSlice = prismic.SharedSlice<
  "content_list",
  ContentListSliceVariation
>;

/**
 * Primary content in *Feature → Default → Primary*
 */
export interface FeatureSliceDefaultPrimary {
  /**
   * H2 field in *Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: If not filled then title will be h2
   * - **API ID Path**: feature.default.primary.heading_2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading_2: prismic.RichTextField;

  /**
   * Title field in *Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Link field in *Feature → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image Position field in *Feature → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Right
   * - **API ID Path**: feature.default.primary.image_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  image_position: prismic.SelectField<"Right" | "Left", "filled">;

  /**
   * Image field in *Feature → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Feature → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: feature.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video: prismic.EmbedField;

  /**
   * Video ratio field in *Feature → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: If the ratio of the video is not 16:9 then enter it here as a number
   * - **API ID Path**: feature.default.primary.video_ratio
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  video_ratio: prismic.NumberField;

  /**
   * Is Hero field in *Feature → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: feature.default.primary.is_hero
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_hero: prismic.BooleanField;

  /**
   * No Padding field in *Feature → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: feature.default.primary.no_padding
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  no_padding: prismic.BooleanField;

  /**
   * Background Colour field in *Feature → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: feature.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_colour: prismic.SelectField<
    "Default" | "Variation 1" | "Variation 2",
    "filled"
  >;
}

/**
 * Default variation for Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Feature*
 */
type FeatureSliceVariation = FeatureSliceDefault;

/**
 * Feature Shared Slice
 *
 * - **API ID**: `feature`
 * - **Description**: Feature
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureSlice = prismic.SharedSlice<
  "feature",
  FeatureSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * H1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: If not filled then title will be h1
   * - **API ID Path**: hero.default.primary.heading_1
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading_1: prismic.RichTextField;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional ctas
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background video field in *Hero → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  background_video: prismic.EmbedField;

  /**
   * Background Video from Media library field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: Add your own compressed video. This can perform faster than Vimeo
   * - **API ID Path**: hero.default.primary.background_video_from_media_library
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  background_video_from_media_library: prismic.LinkToMediaField<
    prismic.FieldState,
    never
  >;

  /**
   * Video ratio field in *Hero → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: If the ratio of the video is not 16:9 then enter it here as a number
   * - **API ID Path**: hero.default.primary.video_ratio
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  video_ratio: prismic.NumberField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *ImageGrid → Default → Primary → Images*
 */
export interface ImageGridSliceDefaultPrimaryImagesItem {
  /**
   * Grid Width field in *ImageGrid → Default → Primary → Images*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose how large the card is on desktop screens
   * - **Default Value**: Half
   * - **API ID Path**: image_grid.default.primary.images[].grid_width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  grid_width: prismic.SelectField<
    "Half" | "Full" | "Third" | "Quarter" | "Two Thirds",
    "filled"
  >;

  /**
   * Image field in *ImageGrid → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *ImageGrid → Default → Primary → Images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.images[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;

  /**
   * Video field in *ImageGrid → Default → Primary → Images*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: Alternative video
   * - **API ID Path**: image_grid.default.primary.images[].video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video: prismic.EmbedField;

  /**
   * Prismic video field in *ImageGrid → Default → Primary → Images*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.images[].prismic_video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  prismic_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Poster image field in *ImageGrid → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.images[].poster_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  poster_image: prismic.ImageField<never>;

  /**
   * Link field in *ImageGrid → Default → Primary → Images*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional link field
   * - **API ID Path**: image_grid.default.primary.images[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Ratio field in *ImageGrid → Default → Primary → Images*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Natural
   * - **API ID Path**: image_grid.default.primary.images[].ratio
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  ratio: prismic.SelectField<
    "Natural" | "Portrait" | "Landscape" | "Square",
    "filled"
  >;
}

/**
 * Primary content in *ImageGrid → Default → Primary*
 */
export interface ImageGridSliceDefaultPrimary {
  /**
   * H2 field in *ImageGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: If not filled then title will be h2
   * - **API ID Path**: image_grid.default.primary.heading_2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading_2: prismic.RichTextField;

  /**
   * Title field in *ImageGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Background Colour field in *ImageGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: image_grid.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_colour: prismic.SelectField<
    "Default" | "Variation 1" | "Variation 2",
    "filled"
  >;

  /**
   * Description field in *ImageGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Images field in *ImageGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<ImageGridSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for ImageGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageGrid*
 */
type ImageGridSliceVariation = ImageGridSliceDefault;

/**
 * ImageGrid Shared Slice
 *
 * - **API ID**: `image_grid`
 * - **Description**: ImageGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageGridSlice = prismic.SharedSlice<
  "image_grid",
  ImageGridSliceVariation
>;

/**
 * Primary content in *LargeMedia → Default → Primary*
 */
export interface LargeMediaSliceDefaultPrimary {
  /**
   * Image field in *LargeMedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: large_media.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *LargeMedia → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: large_media.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video: prismic.EmbedField;

  /**
   * Caption field in *LargeMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: large_media.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;

  /**
   * Cropped field in *LargeMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: large_media.default.primary.cropped
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  cropped: prismic.BooleanField;

  /**
   * Mobile Image field in *LargeMedia → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: large_media.default.primary.mobile_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  mobile_image: prismic.ImageField<never>;

  /**
   * No Padding field in *LargeMedia → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: large_media.default.primary.no_padding
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  no_padding: prismic.BooleanField;

  /**
   * Background Colour field in *LargeMedia → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: large_media.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_colour: prismic.SelectField<
    "Default" | "Variation 1" | "Variation 2",
    "filled"
  >;
}

/**
 * Default variation for LargeMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LargeMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LargeMediaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LargeMedia*
 */
type LargeMediaSliceVariation = LargeMediaSliceDefault;

/**
 * LargeMedia Shared Slice
 *
 * - **API ID**: `large_media`
 * - **Description**: LargeMedia
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LargeMediaSlice = prismic.SharedSlice<
  "large_media",
  LargeMediaSliceVariation
>;

/**
 * Primary content in *SimpleHero → Default → Primary*
 */
export interface SimpleHeroSliceDefaultPrimary {
  /**
   * H1 field in *SimpleHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: If not filled then title will be h1
   * - **API ID Path**: simple_hero.default.primary.heading_1
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading_1: prismic.RichTextField;

  /**
   * Title field in *SimpleHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *SimpleHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short description text
   * - **API ID Path**: simple_hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Background Colour field in *SimpleHero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Default
   * - **API ID Path**: simple_hero.default.primary.background_colour
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_colour: prismic.SelectField<
    "Default" | "Variation 1" | "Variation 2",
    "filled"
  >;

  /**
   * Image field in *SimpleHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: simple_hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for SimpleHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SimpleHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SimpleHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SimpleHero*
 */
type SimpleHeroSliceVariation = SimpleHeroSliceDefault;

/**
 * SimpleHero Shared Slice
 *
 * - **API ID**: `simple_hero`
 * - **Description**: SimpleHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SimpleHeroSlice = prismic.SharedSlice<
  "simple_hero",
  SimpleHeroSliceVariation
>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * H2 field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: If not filled then there will be no H2
   * - **API ID Path**: text.default.primary.heading_2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading_2: prismic.RichTextField;

  /**
   * Text field in *Text → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Text with rich formatting
   * - **API ID Path**: text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Anchor link ID field in *Text → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: To link to this element give it an ID
   * - **API ID Path**: text.default.primary.anchor_link_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_link_id: prismic.KeyTextField;

  /**
   * CTA field in *Text → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Optional CTA button
   * - **API ID Path**: text.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Text Size field in *Text → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a text size
   * - **Default Value**: Default
   * - **API ID Path**: text.default.primary.text_size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  text_size: prismic.SelectField<"Default" | "Large" | "XL", "filled">;

  /**
   * Background Color field in *Text → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a background colour scheme
   * - **Default Value**: Default
   * - **API ID Path**: text.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<
    "Default" | "Variation 1" | "Variation 2",
    "filled"
  >;

  /**
   * Inner Background Colour field in *Text → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: This will make the text sit inside a coloured rectangle
   * - **Default Value**: Default
   * - **API ID Path**: text.default.primary.inner_background_colour
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  inner_background_colour: prismic.SelectField<
    "Default" | "Variation 1" | "Variation 2",
    "filled"
  >;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataLinksItem,
      LayoutDocumentDataLinks1Item,
      LayoutDocumentDataSocialLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      RoomDocument,
      RoomDocumentData,
      RoomDocumentDataFeaturesItem,
      RoomDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccordionSectionSlice,
      AccordionSectionSliceDefaultPrimaryItemsItem,
      AccordionSectionSliceDefaultPrimary,
      AccordionSectionSliceVariation,
      AccordionSectionSliceDefault,
      CardsSlice,
      CardsSliceDefaultPrimaryCardsItem,
      CardsSliceDefaultPrimary,
      CardsSliceVariation,
      CardsSliceDefault,
      ContentListSlice,
      ContentListSliceDefaultPrimaryContentItem,
      ContentListSliceDefaultPrimary,
      ContentListSliceVariation,
      ContentListSliceDefault,
      FeatureSlice,
      FeatureSliceDefaultPrimary,
      FeatureSliceVariation,
      FeatureSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageGridSlice,
      ImageGridSliceDefaultPrimaryImagesItem,
      ImageGridSliceDefaultPrimary,
      ImageGridSliceVariation,
      ImageGridSliceDefault,
      LargeMediaSlice,
      LargeMediaSliceDefaultPrimary,
      LargeMediaSliceVariation,
      LargeMediaSliceDefault,
      SimpleHeroSlice,
      SimpleHeroSliceDefaultPrimary,
      SimpleHeroSliceVariation,
      SimpleHeroSliceDefault,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault,
    };
  }
}
