// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion_section: dynamic(() => import("./AccordionSection")),
  cards: dynamic(() => import("./Cards")),
  content_list: dynamic(() => import("./ContentList")),
  feature: dynamic(() => import("./Feature")),
  hero: dynamic(() => import("./Hero")),
  image_grid: dynamic(() => import("./ImageGrid")),
  large_media: dynamic(() => import("./LargeMedia")),
  simple_hero: dynamic(() => import("./SimpleHero")),
  text: dynamic(() => import("./Text")),
};
