// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  content_list: dynamic(() => import("./ContentList")),
  feature: dynamic(() => import("./Feature")),
  hero: dynamic(() => import("./Hero")),
  image_grid: dynamic(() => import("./ImageGrid")),
  large_media: dynamic(() => import("./LargeMedia")),
  list: dynamic(() => import("./List")),
  text: dynamic(() => import("./Text")),
};
